#!/bin/bash
# Create a test environment for manual experimentation. This should always be keep up-to-date with the unit tests, but there's no guarantee that it will be.

. misc/env.sh
set -ex

mkdir -p /tmp/duseTestEnv

# Create the data.
./misc/createDuseTestData /tmp/duseTestEnv
cd /tmp/duseTestEnv

# Let's configure it.
duse --addContext shoots "Photo shoots"
duse --addSource shoots /tmp/duseTestEnv/source/source1 archiveShoots
duse --addSource shoots /tmp/duseTestEnv/source/source2 primaryShoots # We can have multiple sources, but we don't have to.
duse --setCache shoots /tmp/duseTestEnv/cache

# Create the workspace.
cd projects/example
duse --createWorkspace shoots workspace

# And 
cd workspace
duse --info
duse --listAvailable
duse --use 001
duse --list

duse --listAvailable | duse --use
duse --list
