#!/bin/bash
# Create a test environment for manual experimentation. This should always be keep up-to-date with the unit tests, but there's no guarantee that it will be.

. misc/env.sh
set -ex

mkdir -p /tmp/duseTestEnv

# Create the data.
./misc/createDuseTestData /tmp/duseTestEnv
cd /tmp/duseTestEnv

# Let's configure it.
duse --addContext shootsExample "Photo shoots"
duse --addSource shootsExample /tmp/duseTestEnv/source/source1 archiveShoots
duse --addSource shootsExample /tmp/duseTestEnv/source/source2 primaryShoots # We can have multiple sources, but we don't have to.
duse --setCache shootsExample /tmp/duseTestEnv/cache

# Create the workspace.
cd projects/example
duse --createWorkspace shootsExample workspace1
duse --createWorkspace shootsExample workspace2

# And 
cd workspace1
duse --info
duse --listAvailable
duse --use 001
duse --list

duse --listAvailable | duse --use
duse --cache
duse --list

# duse --uncache 001

# cd ..
# duse --deleteWorkspace workspace

cd ..
cd workspace2
duse --info
duse --listAvailable
duse --use 001
duse --list

duse --listAvailable | duse --use
duse --cache
duse --list

cd ..
pwd
duse --cache
duse --uncache
