#!/bin/bash
# Test --listContext without data.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --listContexts 2>&1)"
exitCode=$?

expect_exitCode 1
expect_resultContains "No contexts yet."
