#!/bin/bash
# Test --listContext without data.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

./bin/duse --listContexts ## Test this.

expect_exitCode 1
expect_errorContains "No contexts yet."
