#!/bin/bash
# Test --addContext.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --addContext shoots "A collection of photo/video shoots.")"
exitCode=$?

./bin/duse --addContext toDelete "An extra context that we will delete in a moment."

expect_exitCode 0
expect_exists "$expectedDuseHome/contexts/shoots"
expect_fileContains "$expectedDuseHome/contexts/shoots"/description "A collection"
