#!/bin/bash
# Test --deleteContext with a non-existant context.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --deleteContext "nonExistant" 2>&1)"
exitCode=$?

expect_exitCode 1
expect_resultContains "not found."
