#!/bin/bash
# Test --deleteContext with a non-existant context.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --deleteContext "nonExistant" 2>&1)"
exitCode=$?

passCode=1
failCode=2


# NOTE that passCode, warnCode, and failCode are not set for you since they may be different depending on what you are testing. Therefore you should either set these values, or replace them with what is meaningful for you.
if echo "$result" | grep -q "not found." && [ "$exitCode" == "$passCode" ] ; then
    pass "Great!"
else
    fail "Something else failed. Got value=\"$result\" and exit code=$exitCode."
fi

