#!/bin/bash
# Test --deleteContext with a non-existant context.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

./bin/duse --deleteContext "nonExistant" ## Test this.

expect_exitCode 1
expect_errorContains "not found."
