#!/bin/bash
# Test --deleteContext.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --deleteContext "toDelete")"
exitCode=$?

expect_exitCode 0
expect_not_exists "$expectedDuseHome/contexts/toDelete"
