#!/bin/bash
# Test --listContext.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

./bin/duse --listContexts ## Test this.

expect_exitCode 0
expect_resultContains "shoots: A collection of photo/video shoots."
