#!/bin/bash
# Test --listContext.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --listContexts)"
exitCode=$?

expect_exitCode 0
expect_resultContains "shoots: A collection of photo/video shoots."
