#!/bin/bash
# Test --addSource.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --addSource shoots source/source1 2>&1)"
exitCode=$?

./bin/duse --addSource shoots source/source2

expect_exitCode 0
expect_exists "$expectedDuseHome/contexts/shoots/sources/source_source1"
expect_exists "$expectedDuseHome/contexts/shoots/sources/source_source2"
