#!/bin/bash
# Test --addSource.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --addSource shoots data/context1 2>&1)"
exitCode=$?

./bin/duse --addSource shoots data/context2

passCode=0
failCode=1

# NOTE that passCode, warnCode, and failCode are not set for you since they may be different depending on what you are testing. Therefore you should either set these values, or replace them with what is meaningful for you.
if [ -e "$expectedDuseHome/contexts/shoots/sources/data_context1" ] && [ -e "$expectedDuseHome/contexts/shoots/sources/data_context2" ]&& [ "$exitCode" == "$passCode" ] ; then
    pass "Great!"
else
    fail "Got \"$result\" with exit code=$exitCode."
fi

