#!/bin/bash
# Test --addSource.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --addSource shoots data/context1 2>&1)"
exitCode=$?

./bin/duse --addSource shoots data/context2

expect_exitCode 0
expect_exists "$expectedDuseHome/contexts/shoots/sources/data_context1"
expect_exists "$expectedDuseHome/contexts/shoots/sources/data_context2"
