#!/bin/bash
# Test --addSource.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

./bin/duse --deleteSource shoots primaryShoots ## Test this.

expect_exitCode 0
expect_not_exists "$expectedDuseHome/contexts/shoots/sources/primaryShoots"
expect_exists "$expectedDuseHome/contexts/shoots/sources/archiveShoots"

# Re-add it so that we have it for future tests.
./bin/duse --addSource shoots source/source2 primaryShoots ## Test this.
expect_exitCode 0
