#!/bin/bash
# Test --addSource.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --deleteSource shoots data/context1)"
exitCode=$?

expect_exitCode 0
expect_not_exists "$expectedDuseHome/contexts/shoots/sources/data_context1"
expect_exists "$expectedDuseHome/contexts/shoots/sources/data_context2"
