#!/bin/bash
# Test that the sources show up in --listContexts.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

./bin/duse --listContexts ## Test this.

expect_exitCode 0
expect_resultContains "archiveShoots"
