#!/bin/bash
# Test that the sources show up in --listContexts.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --listContexts)"
exitCode=$?

expect_exitCode 0
expect_resultContains "archiveShoots"
