#!/bin/bash
# Test --addSource.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --listContexts)"
exitCode=$?

expect_exitCode 0
expect_resultContains "archiveShoots"
