#!/bin/bash
# Test --setCache.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --setCache shoots cache)"
exitCode=$?

expect_exitCode 0
expect_exists "$expectedDuseHome/contexts/shoots/cache/location"
expect_fileContains "$expectedDuseHome/contexts/shoots/cache/location" "cache"
