#!/bin/bash
# Test --setCache.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"

result="$(./bin/duse --setCache shoots nonExistent)"
exitCode=$?

expect_exitCode 1
expect_exists "$expectedDuseHome/contexts/shoots/cache/location"
expect_fileContains "$expectedDuseHome/contexts/shoots/cache/location" "cache"
