#!/bin/bash
# Test --setCache.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"

./bin/duse --setCache shoots nonExistent ## Test this.

expect_exitCode 1
expect_exists "$expectedDuseHome/contexts/shoots/cache/location"
expect_fileContains "$expectedDuseHome/contexts/shoots/cache/location" "cache"
