#!/bin/bash
# Set up for project-wide tests

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
projectHome="$HOME/projects/example"

./bin/duse --addContext shoots "A collection of photo/video shoots." ## Test this.
expect_exitCode 0 "--addContext"

./bin/duse --addSource shoots source/source1 archiveShoots  ## Test this.
expect_exitCode 0 "--addSource archiveShoots"

./bin/duse --addSource shoots source/source2 primaryShoots ## Test this.
expect_exitCode 0 "--addSource primaryShoots"

./bin/duse --setCache shoots cache ## Test this.
expect_exitCode 0 "--setCache"

cd "$projectHome"
$HOME/bin/duse --createWorkspace shoots shoots1 ## Test this.
expect_exitCode 0 "--createWorkspace shoots1"

$HOME/bin/duse --createWorkspace shoots shoots2 ## Test this.
expect_exitCode 0 "--createWorkspace shoots2"


cd "$projectHome/shoots1"
$HOME/bin/duse --listAvailable | sort | head -n3 | $HOME/bin/duse --use ## Test this.
expect_exitCode 0 "Use some shoots in shoots1."

cd "$projectHome/shoots2"
$HOME/bin/duse --listAvailable | sort | tail -n4 | $HOME/bin/duse --use ## Test this.
expect_exitCode 0 "Use some shoots in shoots2 with one overlap (003)."
