#!/bin/bash
# Test project-wide --cache .

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
projectHome="$HOME/projects/example"

cd "$projectHome"
result="$($HOME/bin/duse --cache)"
exitCode=$?
expect_exitCode 0 "--cache"

for dirName in shoots{1,2}; do
  cd "$dirName"
  result="$($HOME/bin/duse --list)"
  exitCode=$?
  expect_exitCode 0 "--list in $dirName."
  
  expect_resultContains "Cached" "Check that all items are cached in $dirName."
  expect_not_resultContains "Uncached" "Check that no items are uncached in $dirName."
  cd ..
done
