#!/bin/bash
# Test project-wide --uncache .

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
projectHome="$HOME/projects/example"

cd "$projectHome"
$HOME/bin/duse --uncache ## Test this.
expect_exitCode 0 "--cache"

for dirName in shoots{1,2}; do
  cd "$dirName"
  $HOME/bin/duse --list ## Test this.
  expect_exitCode 0 "--list in $dirName."
  
  expect_not_resultContains "Cached" "Check that no items are cached in $dirName."
  expect_resultContains "Uncached" "Check that all items are uncached in $dirName."
  cd ..
done
