#!/bin/bash
# Test --createWorkspace.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"
workspaceHomes="$HOME/projects/example/shoots $HOME/projects/example/extra"

cd projects/example

for workspaceHome in $workspaceHomes; do
  ~-/bin/duse --createWorkspace shoots extra
  result="$(~-/bin/duse --createWorkspace shoots shoots 2>&1)"
  exitCode=$?
  
  expect_exitCode 0
  expect_exists "$workspaceHome/.duse/context"
  expect_fileContains "$workspaceHome/.duse/context" "shoots"
  
  name="$(echo "$workspaceHome" | sed "s#\(/\| \)#_#g")"
  expect_exists "$expectedDuseHome/contexts/shoots/workspaces/$name"
  expect_fileContains "$expectedDuseHome/contexts/shoots/workspaces/$name" "$(basename "$workspaceHome")"
done
