#!/bin/bash
# Test --createWorkspace.

. "$SHEST_SCRIPT" "--doNothing"
HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/extra"

cd projects/example
result="$(~-/bin/duse --deleteWorkspace extra 2>&1)"
exitCode=$?

expect_exitCode 0
expect_not_exists "$workspaceHome/.duse/context"
expect_not_exists "$workspaceHome/.duse"
expect_not_exists "$workspaceHome"

name="$(echo "$workspaceHome" | sed "s#\(/\| \)#_#g")"
expect_not_exists "$expectedDuseHome/contexts/shoots/workspaces/$name"
