#!/bin/bash
# Test --createWorkspace.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/extra"

cd projects/example
$HOME/bin/duse --deleteWorkspace extra ## Test this.

expect_exitCode 0
expect_not_exists "$workspaceHome/.duse/context"
expect_not_exists "$workspaceHome/.duse/type"
expect_not_exists "$workspaceHome/.duse"
expect_not_exists "$workspaceHome"

name="$(echo "$workspaceHome" | sed "s#\(/\| \)#_#g")"
expect_not_exists "$expectedDuseHome/contexts/shoots/workspaces/$name"
