#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/shoots"

cd "$workspaceHome"
$HOME/bin/duse --info ## Test this.

expect_exitCode 0
expect_resultContains 'shoots'
expect_resultContains 'A collection of photo/video shoots\.'
expect_resultContains 'source/source1'
expect_resultContains 'source/source2'
