#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

HOME=`pwd`
expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/shoots"

cd "$workspaceHome"
result="$(~-/bin/duse --list)"
exitCode=$?

expect_exitCode 0
expect_resultLines 1
expect_resultContains '^Entry'
