#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/shoots"

cd "$workspaceHome"
result="$($HOME/bin/duse --listAvailable)"
exitCode=$?

expect_exitCode 0
expect_resultContains '^001$'
expect_resultContains '^002$'
expect_resultContains '^003$'
expect_resultContains '^004$'
expect_resultContains '^005$'
expect_resultContains '^006$'
