#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/shoots"

cd "$workspaceHome"
result="$($HOME/bin/duse --use 001)"
exitCode=$?

expect_exitCode 0
expect_exists 001

$HOME/bin/duse --use 001
expect_exitCode 0
expect_exists 001
expect_not_exists 001/001

$HOME/bin/duse --use nonExistant
expect_not_exists nonExistant
