#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/shoots"

cd "$workspaceHome"
$HOME/bin/duse --list ## Test this.

expect_exitCode 0
expect_resultLines 2
expect_resultContains '^Entry'
expect_resultContains 'Yes'
expect_resultContains 'Uncached'
expect_resultContains 'archiveShoots'
