#!/bin/bash
# Test --unuse

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/shoots"

cd "$workspaceHome"
result="$($HOME/bin/duse --unuse 003)"
exitCode=$?
expect_exitCode 0

expect_not_exists "$HOME/cache/shoots/003"
expect_not_exists "$workspaceHome/003"
