#!/bin/bash
# Test --deleteWorkspace

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/shoots"

cd "$workspaceHome"

$HOME/bin/duse --cache ## Test this.
expect_exitCode 0

cd ..

expect_exists "$HOME/cache/shoots/001"
expect_exists "$HOME/cache/shoots/002"
expect_not_exists "$HOME/cache/shoots/003"
expect_exists "$HOME/cache/shoots/004"
expect_exists "$HOME/cache/shoots/005"
expect_exists "$HOME/cache/shoots/006"

$HOME/bin/duse --deleteWorkspace shoots ## Test this.
expect_exitCode 0

expect_not_exists "$HOME/cache/shoots/001"
expect_not_exists "$HOME/cache/shoots/002"
expect_not_exists "$HOME/cache/shoots/003"
expect_not_exists "$HOME/cache/shoots/004"
expect_not_exists "$HOME/cache/shoots/005"
expect_not_exists "$HOME/cache/shoots/006"

expect_not_exists shoots
