#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/shoots"
workspaceName="$(echo "$workspaceHome" | sed "s#\(/\| \)#_#g")"

cd "$workspaceHome"
result="$($HOME/bin/duse --cache 001)"
exitCode=$?

expect_exitCode 0
expect_exists "$HOME/cache/shoots/001"
expect_exists "$HOME/cache/shoots/001/.duse"
expect_exists "$HOME/cache/shoots/001/.duse/usage"
expect_exists "$HOME/cache/shoots/001/.duse/usage/$workspaceName"
expect_exists "$HOME/cache/shoots/001/.duse/source"
expect_exists "$HOME/cache/shoots/001/a"
