#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/shoots"

cd "$workspaceHome"
result="$($HOME/bin/duse --list)"
exitCode=$?

expect_exitCode 0
expect_resultContains ^001.*Cached
