#!/bin/bash
# Write a decription of the test here.

. "$SHEST_SCRIPT" "--doNothing"

expectedDuseHome="$HOME/.config/duse"
workspaceHome="$HOME/projects/example/shoots"

cd "$HOME/projects/example"
$HOME/bin/duse --createWorkspace shoots duplicate ## Test this.
expect_exitCode 0

cd duplicate
$HOME/bin/duse --use 001 ## Test this.
expect_exitCode 0

$HOME/bin/duse --cache 001 ## Test this.
expect_exitCode 0

$HOME/bin/duse --list ## Test this.
expect_exitCode 0
expect_resultContains ^001.*Cached

ls -1 "$HOME/cache/shoots/001/.duse/usage" | wc -l ## Test this.
expect_exitCode 0
expect_value "$result" "2"

